function [out] = extractData(file)



%% Import data from text file.
% Script for importing data from the following text file:
%
%    /media/steven/Windows/Users/Steven/Google Drive/Thesis/Data/Fly_Decawave_onboard_Kalman/08-09-2017/rlLogFile_2017-09-08-16_45_28_IP25_SPIRAL1.txt
%
% To extend the code to different selected data or a different text file,
% generate a function instead of a script.

% Auto-generated by MATLAB on 2017/09/12 11:45:51

%% Initialize variables.

delimiter = ',';
startRow = 2;

%% Format for each line of text:
%   column1: double (%f)
%	column2: double (%f)
%   column3: double (%f)
%	column4: double (%f)
%   column5: double (%f)
%	column6: double (%f)
%   column7: double (%f)
%	column8: double (%f)
%   column9: double (%f)
%	column10: double (%f)
%   column11: double (%f)
%	column12: double (%f)
%   column13: double (%f)
%	column14: double (%f)
%   column15: double (%f)
%	column16: double (%f)
%   column17: double (%f)
%	column18: double (%f)
%   column19: double (%f)
%	column20: double (%f)
%   column21: double (%f)
% For more information, see the TEXTSCAN documentation.
formatSpec = '%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%[^\n\r]';

%% Open the text file.
fileID = fopen(file,'r');

%% Read columns of data according to the format.
% This call is based on the structure of the file used to generate this
% code. If an error occurs for a different file, try regenerating the code
% from the Import Tool.
dataArray = textscan(fileID, formatSpec, 'Delimiter', delimiter, 'TextType', 'string', 'EmptyValue', NaN, 'HeaderLines' ,startRow-1, 'ReturnOnError', false, 'EndOfLine', '\r\n');
numrowarr = ones(1,size(dataArray,2));
for i=1:size(dataArray,2)
    numrowarr(i) = size(dataArray{i},1);
end
maxrows = max(numrowarr);
minrows = min(numrowarr);

if (maxrows~=minrows)
    stopline = maxrows-minrows;
    for i=1:size(dataArray,2)
        if (size(dataArray{i},1)==maxrows)
            dataArray{i} = dataArray{i}(1:end-stopline);
        end
    end
end

%% Close the text file.
fclose(fileID);

%% Post processing for unimportable data.
% No unimportable data rules were applied during the import, so no post
% processing code is included. To generate code which works for
% unimportable data, select unimportable cells in a file and regenerate the
% script.

%% Create output variable
out = table(dataArray{1:end-1}, 'VariableNames', {'msg_count','AC_ID','time','dt','own_x','own_y','own_z','own_vx','own_vy','own_vz','Range','track_vx_meas','track_vy_meas','track_z_meas','kal_x','kal_y','kal_vx','kal_vy','kal_oth_vx','kal_oth_vy','kal_rel_h','kal_bias'});

%% Clear temporary variables
clearvars filename delimiter startRow formatSpec fileID dataArray ans;
end